[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/insights-meta"
  to = "/.netlify/functions/fb-insights"
  status = 200

[[redirects]]
  from = "/api/insights-google"
  to = "/.netlify/functions/google-insights"
  status = 200

[[redirects]]
  from = "/api/insights-tiktok"
  to = "/.netlify/functions/tiktok-insights"
  status = 200

[[redirects]]
  from = "/api/sales"
  to = "/.netlify/functions/sales"
  status = 200

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/settings"
  to = "/.netlify/functions/settings"
  status = 200
